version: "2"
services:
    mysql:
        build         : ./mysql
        container_name: mysql_ginipig
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE     : mysql_ginipig
            MYSQL_USER         : ginipig
            MYSQL_PASSWORD     : root
            MYSQL_ROOT_PASSWORD: root